### ISSUE TITLE
[Simutrans Android] Airports are broken, "Can't Find a Route"

### ISSUE THREAD

**Issue by chacalbl4ck** [simutrans/simutrans#2]
When using airports, planes can't find a route.

Pieces used in 2 airports:
1 Runaway
1 Taxiway
1 Stop point
1 Depot

Configured a route in route manager.

This configuration works on PC but not in Android.

Info about game and hardware:
Using the latest version on Play Store.
Using Pak 128.
Poco X3 Pro
Android 12 and MIUI 13.

![Screenshot_2023-07-28-23-07-49-224_com.simutrans.jpg](https://github.com/simutrans/simutrans/assets/38815703/6c8be997-64f2-4a8e-ac82-9841a6dec722)

**Comment by ceeac** [comment]
Since this repository is just a mirror, I have opened a bug report thread on the forum (https://forum.simutrans.com/index.php/topic,22390.0.html). Please post your (Android) save file there, if possible.

**Comment by chacalbl4ck** [comment]
Issue closed due post on wrong place. You can find the progress of this issue on the link provided by @ceeac.
https://forum.simutrans.com/index.php/topic,22390.0.html
